// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $api_trpc_ from './routes/api/[trpc].ts'
import * as $index from './routes/index.tsx'
import * as $market_middleware from './routes/market/_middleware.ts'
import * as $market_index from './routes/market/index.tsx'
import * as $property_market_id_ from './routes/property/[market_id].tsx'
import * as $property_middleware from './routes/property/_middleware.ts'
import * as $Carousel from './islands/Carousel.tsx'
import * as $Property from './islands/Property.tsx'
import * as $Provider from './islands/Provider.tsx'
import { type Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/api/[trpc].ts': $api_trpc_,
    './routes/index.tsx': $index,
    './routes/market/_middleware.ts': $market_middleware,
    './routes/market/index.tsx': $market_index,
    './routes/property/[market_id].tsx': $property_market_id_,
    './routes/property/_middleware.ts': $property_middleware,
  },
  islands: {
    './islands/Carousel.tsx': $Carousel,
    './islands/Property.tsx': $Property,
    './islands/Provider.tsx': $Provider,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
